# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: 'AgentDeadPool'

steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '8.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet
        
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
      checkLatest: true

  - script: |
      apt-get update
      apt-get install -y docker.io
    displayName: 'Install Docker CLI'

  - script: |
      echo "Dotnet version:"
      dotnet --version
      echo "Node version:"
      node --version
      echo "Npm version:"
      npm --version
      echo "Docker version:"
      docker --version
    displayName: 'Verify Tools Installed'

  - script: dotnet restore
    displayName: 'Restore NuGet packages'

  - script: dotnet build --configuration Release --no-restore
    displayName: 'Build .NET app'

  - script: dotnet test --no-build --verbosity normal
    displayName: 'Run Tests'

